<?php declare(strict_types=1);

namespace XoopsModules\Xsitemap;

/*
 * ****************************************************************************
 * Module generated by TDMCreate from TDM "https://www.tdmxoops.net"
 * ****************************************************************************
 * xsitemap - MODULE FOR XOOPS CMS
 * Copyright (c) Urbanspaceman (https://www.takeaweb.it)
 *
 * You may not change or alter any portion of this comment or credits
 * of supporting developers from this source code or any supporting source code
 * which is considered copyrighted (c) material of the original comment or credit authors.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

/**
 * Module: xsitemap
 *
 * @author     Urbanspaceman (https://www.takeaweb.it)
 * @copyright  Urbanspaceman (https://www.takeaweb.it)
 * @license    https://www.fsf.org/copyleft/gpl.html GNU public license
 * @since      1.00
 */
class DummyObject extends \XoopsObject
{
    /**
     * constructor
     * @param        $row
     * @param string $id_name
     * @param string $pid_name
     * @param string $title_name
     */
    public function __construct($row, string $id_name = 'cid', string $pid_name = 'pid', string $title_name = 'title')
    {
        parent::__construct();
        $this->initVar($id_name, \XOBJ_DTYPE_INT, $row[$id_name]);
        $this->initVar($pid_name, \XOBJ_DTYPE_INT, $row[$pid_name]);
        $this->initVar($title_name, \XOBJ_DTYPE_TXTBOX, $row[$title_name]);
    }
}
